# Generated by Django 3.0.5 on 2020-10-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=18)),
                ('student_grade', models.CharField(max_length=200)),
                ('master_class', models.CharField(default='computer science', max_length=200)),
                ('description', models.TextField(default="I'm student. I'm studying at the <django.db.models.fields.CharField> department in XNXX University!", max_length=1000)),
            ],
        ),
    ]
